No package files given... Grabbing a set.
--- replaced obj /usr/share/man/man8/rmmod.8.bz2
--- replaced obj /usr/share/man/man8/modprobe.8.bz2
--- replaced obj /usr/share/man/man8/modinfo.8.bz2
--- replaced obj /usr/share/man/man8/lsmod.8.bz2
--- replaced obj /usr/share/man/man8/kmod.8.bz2
--- replaced obj /usr/share/man/man8/insmod.8.bz2
--- replaced obj /usr/share/man/man8/depmod.8.bz2
--- replaced dir /usr/share/man/man8
--- replaced obj /usr/share/man/man5/modules.dep.bin.5
--- replaced obj /usr/share/man/man5/modules.dep.5.bz2
--- replaced obj /usr/share/man/man5/modprobe.d.5.bz2
--- replaced obj /usr/share/man/man5/depmod.d.5.bz2
--- replaced dir /usr/share/man/man5
--- replaced dir /usr/share/man
--- replaced obj /usr/share/bash-completion/completions/kmod
--- replaced dir /usr/share/bash-completion/completions
--- replaced dir /usr/share/bash-completion
--- replaced dir /usr/share
--- replaced obj /usr/lib64/pkgconfig/libkmod.pc
--- replaced dir /usr/lib64/pkgconfig
--- replaced sym /usr/lib64/libkmod.so
--- replaced dir /usr/lib64
--- replaced obj /usr/lib/python3.8/site-packages/kmod/version.py
--- replaced obj /usr/lib/python3.8/site-packages/kmod/module.so
--- replaced obj /usr/lib/python3.8/site-packages/kmod/list.so
--- replaced obj /usr/lib/python3.8/site-packages/kmod/kmod.so
--- replaced obj /usr/lib/python3.8/site-packages/kmod/error.py
--- replaced obj /usr/lib/python3.8/site-packages/kmod/_util.so
--- replaced obj /usr/lib/python3.8/site-packages/kmod/__pycache__/version.cpython-38.pyc
--- replaced obj /usr/lib/python3.8/site-packages/kmod/__pycache__/version.cpython-38.opt-2.pyc
--- replaced obj /usr/lib/python3.8/site-packages/kmod/__pycache__/version.cpython-38.opt-1.pyc
--- replaced obj /usr/lib/python3.8/site-packages/kmod/__pycache__/error.cpython-38.pyc
--- replaced obj /usr/lib/python3.8/site-packages/kmod/__pycache__/error.cpython-38.opt-2.pyc
--- replaced obj /usr/lib/python3.8/site-packages/kmod/__pycache__/error.cpython-38.opt-1.pyc
--- replaced obj /usr/lib/python3.8/site-packages/kmod/__pycache__/__init__.cpython-38.pyc
--- replaced obj /usr/lib/python3.8/site-packages/kmod/__pycache__/__init__.cpython-38.opt-2.pyc
--- replaced obj /usr/lib/python3.8/site-packages/kmod/__pycache__/__init__.cpython-38.opt-1.pyc
--- replaced dir /usr/lib/python3.8/site-packages/kmod/__pycache__
--- replaced obj /usr/lib/python3.8/site-packages/kmod/__init__.py
--- replaced dir /usr/lib/python3.8/site-packages/kmod
--- replaced dir /usr/lib/python3.8/site-packages
--- replaced dir /usr/lib/python3.8
--- replaced dir /usr/lib
--- replaced obj /usr/include/libkmod.h
--- replaced dir /usr/include
--- replaced dir /usr
--- replaced sym /sbin/rmmod
--- replaced sym /sbin/modprobe
--- replaced sym /sbin/insmod
--- replaced sym /sbin/depmod
--- replaced dir /sbin
--- replaced obj /lib64/libkmod.so.2.3.5
--- replaced sym /lib64/libkmod.so.2
--- replaced dir /lib64
--- replaced obj /lib/modprobe.d/usb-load-ehci-first.conf
--- replaced dir /lib/modprobe.d
--- replaced dir /lib
--- replaced obj /etc/init.d/kmod-static-nodes
--- replaced dir /etc/init.d
--- replaced dir /etc
--- replaced sym /bin/modinfo
--- replaced sym /bin/lsmod
--- replaced obj /bin/kmod
--- replaced dir /bin
>>> Regenerating /etc/ld.so.cache...
